# The Sparks Foundation
## Task -2 : Regression task where we will predict the percentage of marks that a student is expected to score based upon the number of hours they studied.

### Importing libraries

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

### Importing Datasets

In [4]:
df=pd.read_csv('D:\Sparks foundation\Second task\data.csv')

In [5]:
df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [6]:
df.notnull()

Hours  Scores
0    True    True
1    True    True
2    True    True
3    True    True
4    True    True
5    True    True
6    True    True
7    True    True
8    True    True
9    True    True
10   True    True
11   True    True
12   True    True
13   True    True
14   True    True
15   True    True
16   True    True
17   True    True
18   True    True
19   True    True
20   True    True
21   True    True
22   True    True
23   True    True
24   True    True

In [7]:
X=df.iloc[:,:-1].values

In [8]:
y=df.iloc[:,-1].values

### Splitting into training and test sets

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

### Training the model with train data sets

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr=LinearRegression()

In [13]:
lr.fit(x_train,y_train)

LinearRegression()

### Predicting the test set data

In [14]:
y_pred=lr.predict(x_test)

In [15]:
y_pred

array([16.88414476, 33.73226078, 75.357018  , 26.79480124, 60.49103328])

### Predicting new result

In [22]:
lr.predict([[9.25]])

array([93.69173249])

### Creating an array with actual and predicted values for observation

In [16]:
con=(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

In [17]:
con

array([[16.88414476, 20.        ],
       [33.73226078, 27.        ],
       [75.357018  , 69.        ],
       [26.79480124, 30.        ],
       [60.49103328, 62.        ]])

In [18]:
lr.predict([[4.2]])

array([43.64291726])

### Evaluating the model

In [19]:
from sklearn.metrics import mean_absolute_error, r2_score

In [20]:
print('Mean squared error: %.2f'
      % mean_absolute_error(y_test,y_pred))

Mean squared error: 4.18


In [21]:
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Coefficient of determination: 0.95
